### ISSUE TITLE
squadron_builder is not generating `cancelAll` method required by squadron v6.2.0

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron_builder#28]
I tried using the latest `squadron` **v6.2.0** with `squadron_builder` **v6.1.5** and I get this error:

```
Error (Xcode): lib/src/core/api/data/service/json_service.worker.g.dart:200:12: Error: The non-abstract class 'JsonServiceWorkerPool' is missing implementations for these members:

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

Upon further inspection I noticed that the `cancelAll` method is not getting generated. Additionally I noticed that in the generated file `json_service.worker.g.dart` 

```dart
@override
void cancel([Task? task, String? message]) => _$pool.cancel(task, message);
```

will also throw a typye error
```
The argument type 'Task<dynamic>?' can't be assigned to the parameter type 'Task<dynamic>'.
```

My `json_service.dart` is very basic

```dart
// ignore_for_file: depend_on_referenced_packages
import 'dart:async';
import 'dart:convert' show jsonDecode;

import 'package:cancelation_token/cancelation_token.dart';
import 'package:logger/logger.dart';
import 'package:squadron/squadron.dart';
import 'package:using/using.dart';

import 'json_service.activator.g.dart';

part 'json_service.worker.g.dart';

@SquadronService.vm()
base class JsonService {
  @squadronMethod
  FutureOr<dynamic> decode(String source) => jsonDecode(source);
}
```

and my `build.yaml` is

```yaml
targets:
  $default:
    builders:
      squadron_builder:worker_builder:
        options:
          with_finalizers: true
          serialization_type: List
```
