### ISSUE TITLE
InconsistentAnalysisException

### ISSUE THREAD

**Issue by techouse** [d-markey/squadron_builder#6]
Hey! :)

Just tried running code generation with v2.3.0 and I get this `[SEVERE]` error:

```
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

It works fine when trying with the commit hash be8aa56bf5ff0656d0e94e4ebf72c0f592afad45 (v2.2.1)

```yaml
dependency_overrides:
  squadron_builder:
    git:
      url: git@github.com:d-markey/squadron_builder.git
      ref: be8aa56bf5ff0656d0e94e4ebf72c0f592afad45
```

so looks like some change in this commit 00fd7f67ff683848f0e458941ed0010d515be202 broke it

**Comment by d-markey** [comment]
Darn sorry :-( Never came across that one. Is it the same JsonService as in the other ticket? I don't know how to reproduce this issue, do you have any stack trace or additional info? I suspect this might come from `final library = await buildStep.inputLibrary;` in the new `BuildStepCodeEvent` class. Do you have several services defined in the same file?

**Comment by techouse** [comment]
Yeah, I only have that one `JsonService`.

```dart
@SquadronService(web: false)
class JsonService extends WorkerService with $JsonServiceOperations {
  @SquadronMethod()
  Future<dynamic> decode(String source) async => jsonDecode(source);
}
```

Funny enough, this error comes from different files every time I clear the build cache. All of them not-related to squadron or any services. Sometimes it's a file that uses `json_serializable`, sometimes a file using `autoequal`, sometimes a file using `mockito`. It's weird. 🤪

**Comment by d-markey** [comment]
I suspect something related to multithreading/async. I've migrated async code to sync hoping it will help with this issue... but I can't reproduce. There are several reports of issues with `InconsistentAnalysisException` when multiple builders are used. Maybe ordering builders one way or another could also help on your side?

**Comment by techouse** [comment]
I tried with the latest commit you made b409aa401475b52c1f21144b68a78be138f67e82

```yaml
dependency_overrides:
  squadron_builder:
    git:
      url: https://github.com/d-markey/squadron_builder.git
      ref: b409aa401475b52c1f21144b68a78be138f67e82
```

and I still get the error. Still with random unrelated files.

My `build.yaml` file is pretty simple

```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
      squadron_builder:worker_builder:
        options:
          with_finalizers: true
          serialization_type: List
```

**Comment by d-markey** [comment]
New push available, should be fixed now!

**Comment by techouse** [comment]
I can confirm that testing it with the latest commit 35f0b02ed8478f52d896979c7bf48b1666e126a4

```yaml
dependency_overrides:
  squadron_builder:
    git:
      url: https://github.com/d-markey/squadron_builder.git
      ref: 35f0b02ed8478f52d896979c7bf48b1666e126a4
```

the code generation works as expected ✅

Great work as always 🚀

I'm closing the issue as resolved.
